-- ─────────────────────────────────────────────────────────────────────────────
-- Jax AI upgrade tables
--
-- Creates:
--   jax_documents       — AI-generated clinical and administrative documents
--   agent_conversations — Conversation history for the Jax AI assistant
--   jax_form_registry   — Registry of platform forms the AI can fill/submit
--   jax_notifications   — In-platform notifications created by the monitor handler
--
-- Alters:
--   clients_1777020684735 — Adds clinical_notes jsonb column for AI-updated notes
--
-- All changes are idempotent (IF NOT EXISTS / ADD COLUMN IF NOT EXISTS).
-- ─────────────────────────────────────────────────────────────────────────────

-- ── jax_documents ─────────────────────────────────────────────────────────────
-- Stores documents generated by Jax (progress notes, referrals, care plans, etc.)
-- Requires clinician review before use (requires_review = true by default).

CREATE TABLE IF NOT EXISTS jax_documents (
  id               uuid        DEFAULT gen_random_uuid() PRIMARY KEY,
  name             text        NOT NULL,
  type             text        NOT NULL,
  content          text        NOT NULL,
  content_html     text,
  location_id      uuid,
  created_by       uuid        REFERENCES auth.users(id),
  client_id        uuid,
  provider_id      uuid,
  status           text        DEFAULT 'draft',
  jax_generated    boolean     DEFAULT true,
  requires_review  boolean     DEFAULT true,
  reviewed_by      uuid,
  reviewed_at      timestamptz,
  metadata         jsonb       DEFAULT '{}',
  created_at       timestamptz DEFAULT now(),
  updated_at       timestamptz DEFAULT now()
);

-- Index for fast lookup by client and creator
CREATE INDEX IF NOT EXISTS idx_jax_documents_client_id   ON jax_documents (client_id);
CREATE INDEX IF NOT EXISTS idx_jax_documents_created_by  ON jax_documents (created_by);
CREATE INDEX IF NOT EXISTS idx_jax_documents_status      ON jax_documents (status);

-- ── agent_conversations ────────────────────────────────────────────────────────
-- Stores conversation history per user session for context continuity.

CREATE TABLE IF NOT EXISTS agent_conversations (
  id         uuid        DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id    uuid        REFERENCES auth.users(id),
  session_id uuid        DEFAULT gen_random_uuid(),
  messages   jsonb       DEFAULT '[]',
  context    jsonb       DEFAULT '{}',
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_agent_conversations_user_id    ON agent_conversations (user_id);
CREATE INDEX IF NOT EXISTS idx_agent_conversations_session_id ON agent_conversations (session_id);

-- ── jax_form_registry ─────────────────────────────────────────────────────────
-- Maps logical form IDs to platform routes and their Supabase target tables.
-- Populated by the platform's form registration process.

CREATE TABLE IF NOT EXISTS jax_form_registry (
  id              uuid        DEFAULT gen_random_uuid() PRIMARY KEY,
  form_id         text        UNIQUE NOT NULL,
  form_name       text        NOT NULL,
  route           text,
  fields          jsonb       NOT NULL,
  supabase_table  text,
  created_at      timestamptz DEFAULT now()
);

-- ── jax_notifications ─────────────────────────────────────────────────────────
-- In-platform notifications created by the jax-monitor background handler.
-- Supports role-based and user-specific targeting.

CREATE TABLE IF NOT EXISTS jax_notifications (
  id             uuid        DEFAULT gen_random_uuid() PRIMARY KEY,
  location_id    uuid,
  recipient_id   uuid        REFERENCES auth.users(id),
  recipient_role text,
  title          text        NOT NULL,
  message        text        NOT NULL,
  urgency        text        DEFAULT 'info',
  entity_type    text,
  entity_id      uuid,
  route          text,
  read           boolean     DEFAULT false,
  dismissed      boolean     DEFAULT false,
  created_at     timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_jax_notifications_recipient_id   ON jax_notifications (recipient_id);
CREATE INDEX IF NOT EXISTS idx_jax_notifications_recipient_role ON jax_notifications (recipient_role);
CREATE INDEX IF NOT EXISTS idx_jax_notifications_urgency        ON jax_notifications (urgency);
CREATE INDEX IF NOT EXISTS idx_jax_notifications_read           ON jax_notifications (read) WHERE read = false;

-- ── clients_1777020684735 — add clinical_notes column ─────────────────────────
-- Stores an array of AI-assisted clinical notes in JSONB format.
-- Each element: { id, type, content, author_id, created_at }

ALTER TABLE clients_1777020684735
  ADD COLUMN IF NOT EXISTS clinical_notes jsonb DEFAULT '[]';

-- ── Row Level Security ─────────────────────────────────────────────────────────
-- Enable RLS on all new tables. Service role bypasses all policies.
-- Application-level access is controlled by Netlify function authentication.

ALTER TABLE jax_documents        ENABLE ROW LEVEL SECURITY;
ALTER TABLE agent_conversations  ENABLE ROW LEVEL SECURITY;
ALTER TABLE jax_form_registry    ENABLE ROW LEVEL SECURITY;
ALTER TABLE jax_notifications    ENABLE ROW LEVEL SECURITY;

-- jax_documents: authenticated users can read their own documents; service role can do all
CREATE POLICY IF NOT EXISTS "jax_documents_select_own"
  ON jax_documents FOR SELECT
  USING (auth.uid() = created_by);

CREATE POLICY IF NOT EXISTS "jax_documents_insert_own"
  ON jax_documents FOR INSERT
  WITH CHECK (auth.uid() = created_by);

CREATE POLICY IF NOT EXISTS "jax_documents_update_own"
  ON jax_documents FOR UPDATE
  USING (auth.uid() = created_by);

-- agent_conversations: users can only access their own conversations
CREATE POLICY IF NOT EXISTS "agent_conversations_select_own"
  ON agent_conversations FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY IF NOT EXISTS "agent_conversations_insert_own"
  ON agent_conversations FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY IF NOT EXISTS "agent_conversations_update_own"
  ON agent_conversations FOR UPDATE
  USING (auth.uid() = user_id);

-- jax_form_registry: readable only by admin+ roles (contains internal table/field schema)
-- Staff and field_agents access forms via the submit_form tool (server-side, service role)
CREATE POLICY IF NOT EXISTS "jax_form_registry_select_admin"
  ON jax_form_registry FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM admin_users_1777025000000
      WHERE user_id = auth.uid()
        AND role IN ('sysadmin', 'admin')
    )
  );

-- jax_notifications: users can read their own notifications
CREATE POLICY IF NOT EXISTS "jax_notifications_select_own"
  ON jax_notifications FOR SELECT
  USING (auth.uid() = recipient_id);

CREATE POLICY IF NOT EXISTS "jax_notifications_update_own"
  ON jax_notifications FOR UPDATE
  USING (auth.uid() = recipient_id);
